blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('home/', BlogListView.as_view(), name='home'),
    path('home/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('home/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('home/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    objects = None
    name = models.CharField(
        max_length=150, verbose_name="Заголовок", help_text="Введите заголовок"
    )

    content = models.TextField(
        verbose_name="Содержимое",
        help_text="Введите содержимое продукта",
        null=False,
    )

    image = models.ImageField(
        upload_to="blog/photo",
        verbose_name="Изображение",
        help_text="Добавьте изображение продукта",
    )

    created_at = models.DateField(
        auto_now_add=True,
    )

    sign_publication = models.BooleanField(
        default=True
    )

    view_count = models.PositiveIntegerField(
        verbose_name="Счётчик просмотров",
        default=0,
    )

blog/views.py
from django.views.generic import DetailView, ListView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy, reverse
from .models import Blog
from django.shortcuts import render


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/home.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        return Blog.objects.filter(sign_publication=True)


class BlogCreateView(CreateView):
    model = Blog
    fields = ['name', 'content', 'image', 'view_count', 'sign_publication']
    template_name = 'blog/blog_form.html'
    success_url = reverse_lazy('blog:home')


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog.html'
    context_object_name = 'blog'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['name', 'content', 'image', 'view_count', 'sign_publication']
    template_name = 'blog/blog_form.html'
    success_url = reverse_lazy('blog:home')

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blog/blog_delete.html'
    success_url = reverse_lazy('blog:home')

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Блог</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
</head>
{% include 'blog/includes/inc_menu.html'%}
{% block content %}
{% endblock %}
<body>
{% include 'blog/includes/inc_footer.html'%}
    <script type="text/javascript" src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/blog.html
{% extends 'blog/base.html'%}
{% load my_tag %}
{% block content %}
<div class="card mb-3">
  <img src="{{ blog.image| media_filter }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ blog.name }}</h5>
    <p class="card-text"> {{ blog.content }}</p>
    <p class="card-text"><small class="text-muted"> Количество просмотров: {{blog.view_count}}</small></p>
    <p class="card-text"><small class="text-muted">{{blog.created_at}}</small></p>
      <a href="{% url 'blog:blog_update' blog.id %}" class="btn btn-primary">Редактировать</a>
      <a href="{% url 'blog:blog_delete' blog.id %}" class="btn btn-danger">Удалить</a>
  </div>
</div>
{% endblock %}

blog/templates/blog/blog_delete.html
{% extends 'blog/base.html'%}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Удалить пост </h1>
        <p>Вы уверены, что хотите удалить "{{ object.name }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'blog:blog_detail' blog.id %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html'%}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Добавить пост</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'blog:home' %}" class="btn btn-secondary">Отмена</a>
        </form>
</div>
{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html'%}
{% load my_tag %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Мой Блог</h1>
<div class="container mt-5">
    <div class="row text-center">
        {% for blog in blogs %}
        <div class="col-3">
            <div class="card" style="width: 18rem;">
              <img src="{{ blog.image | media_filter }}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">{{ blog.name }}</h5>
                <p class="card-text">{{ blog.content|truncatechars:100 }}</p>
                <a href="{% url 'blog:blog_detail' blog.id %}" class="btn btn-primary">Читать</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}