blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('home/', BlogListView.as_view(), name='home'),
    path('home/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('home/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('home/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete')
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import home, ContactsView, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path("", home, name="home"),
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("products/", ProductListView.as_view(), name="product_list"),
    path("product/<int:pk>", ProductDetailView.as_view(), name="product_detail"),
    path("create", ProductCreateView.as_view(), name="product_create"),
    path("product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=150, verbose_name="Название", help_text="Введите название", unique=True,
    )
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]


class Product(models.Model):
    name = models.CharField(
        max_length=150, verbose_name="Название", help_text="Введите название"
    )
    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание продукта",
        blank=True,
        null=True,
    )
    image = models.ImageField(
        upload_to="catalog/photo",
        blank=True,
        null=True,
        verbose_name="Изображение",
        help_text="Добавьте изображение продукта",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="Категория",
        help_text="Введите категорию продукта",
        related_name="catalog",
    )
    price = models.DecimalField(
        verbose_name="Цена",
        max_digits=10,
        decimal_places=2,
        null=False,
        default=0.00,
    )
    created_at = models.DateField(
        auto_now_add=True,
    )
    updated_at = models.DateField(
        auto_now=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name"]

catalog/forms.py
from django import forms

from catalog.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите название продукта'
        })

        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите описание продукта'
        })

        self.fields['image'].widget.attrs.update({
            'class': 'form-control',
        })

        self.fields['category'].widget.attrs.update({
            'class': 'form-control',
        })

        self.fields['price'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите цену продукта',
        })


    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')

        if name.lower() in ["казино", "криптовалюта", "крипта", "биржа", "дешево",
                            "бесплатно", "обман", "полиция", "радар"]:
            self.add_error('name', 'Запрещённое слово.')

        if description.lower() in ["казино", "криптовалюта", "крипта", "биржа", "дешево",
                            "бесплатно", "обман", "полиция", "радар"]:
            self.add_error('description', 'Запрещённое слово.')


    def clean_price(self):
        cleaned_data = super().clean()
        price = cleaned_data.get('price')

        if price < 0:
            raise forms.ValidationError("Стоимость продукта не может быть отрицательной.")

        if price == 0:
            raise forms.ValidationError("Стоимость продукта должна быть указана.")

        return price

catalog/views.py
from audioop import reverse

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View

from django.http import HttpResponse
from django.shortcuts import render

from catalog.forms import ProductForm
from catalog.models import Product


def home(request):
    """Контроллер для домашней страницы."""
    return render(request, "catalog/home.html")


class ContactsView(View):
    @staticmethod
    def get(request):
        return render(request, 'catalog/contacts.html')

    @staticmethod
    def post(request):
        name = request.POST.get('name')
        massage = request.POST.get('massage')
        return HttpResponse(f"Спасибо, {name}. Сообщение получено.")


class ProductListView(ListView):
    model = Product
    template_name = "catalog/product_list.html"
    context_object_name = "product_list"


class ProductDetailView(DetailView):
    model = Product
    template_name = "catalog/product_detail.html"
    context_object_name = "product"


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    success_url = reverse_lazy("catalog:product_list")


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    success_url = reverse_lazy("catalog:product_list")


    def get_success_url(self):
        return reverse("catalog:product_detail", args=[self.kwargs.get("pk")])


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")

catalog/templates/catalog/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Skystore {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">

</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}

{% block content %}
{% endblock %}

{% include 'catalog/includes/inc_footer.html' %}

<script type="text/javascript" src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends "base.html" %}

{% block title %} Контакты {% endblock %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends "catalog/base.html" %}

{% block title %} Главная страница {% endblock %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Список продуктов</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Список всех продуктов</li>
                    </ul>
                    <a href="{% url 'catalog:product_list'%}" class="btn btn-lg btn-block btn-outline-primary">Перейти к
                        товарам</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_create.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                      {% if object %}
                      Сохранить
                      {% else %}
                      Создать
                      {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends "base.html" %}
{% load my_tags %}
{% block title %} Подробнее о продукте {% endblock %}

{% block content %}
<div class="row text-center">
    <div class="card" style="width: 18rem;">
        <img src="{{ product.image | media_filter }}" class="card-img-top" alt="product">
        <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <h4 class="card-text">{{ product.price }}</h4>
            <p class="card-text">{{ product.description|truncatechars:100 }}</p>
            <p class="card-text">{{ product.category}}</p>
            <a href="#" class="btn btn-primary">Купить</a>
            <a href="{% url 'catalog:home' %}" class="btn btn-primary">Назад на главную</a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.non_field_error }}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                      {% if object %}
                      Сохранить
                      {% else %}
                      Создать
                      {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html'%}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    {% for product in object_list %}
    <div class="card" style="width: 18rem;">
        <img src="{{ product.image | media_filter }}" class="card-img-top" alt="product">
        <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <h4 class="card-text">{{ product.price }}</h4>
            <p class="card-text">{{ product.description|truncatechars:100 }}</p>
            <a href="{% url 'catalog:product_detail' product.id %}" class="btn btn-primary">Подробнее о товаре</a>
            <a href="{% url 'catalog:product_update' product.id %}" class="btn btn-secondary">Редактировать</a>
            <a href="{% url 'catalog:product_delete' product.id %}" class="btn btn-danger">Удалить</a>
            <a href="{% url 'catalog:home' %}" class="btn btn-success">Назад</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}